# Generated by Django 3.1.5 on 2021-01-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0002_delete_product_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
