# Generated by Django 3.1.5 on 2021-01-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0004_auto_20210125_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signup_confirmation',
        ),
    ]
