# Generated by Django 3.1.5 on 2021-01-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0005_remove_profile_signup_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1200)),
                ('product_quantity', models.CharField(max_length=1200)),
                ('status', models.CharField(choices=[('BOUGHT', 'BOUGHT'), ('NOT AVAILABLE', 'NOT AVAILABLE'), ('PENDING', 'PENDING')], default='BOUGHT', max_length=1200)),
                ('date', models.DateField()),
            ],
        ),
    ]
