# Generated by Django 3.1.5 on 2021-01-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0006_product_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='status',
            field=models.CharField(choices=[('BOUGHT', 'BOUGHT'), ('NOT AVAILABLE', 'NOT AVAILABLE'), ('PENDING', 'PENDING')], max_length=1200),
        ),
    ]
