# Generated by Django 3.1.5 on 2021-01-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0007_auto_20210125_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_list',
            new_name='Product',
        ),
    ]
